### ISSUE TITLE
regex_injection_dos false positive

### ISSUE THREAD

**Issue by jonny64** [ajinabraham/njsscan#104]
why `any .split (options.arg)` is prohibited pattern ?

https://github.com/ajinabraham/njsscan/blob/75bfbeb9c8d72999e4d527dfa2548f7f0f3cc48a/njsscan/rules/semantic_grep/dos/regex_injection.yaml#L56

looked for this in git blame and found no anwser: it looks like this since first version, there us no test for this case

should I pull to remove this?

**Comment by ajinabraham** [comment]
Split takes a [regex](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split#splitting_with_a_regexp_to_include_parts_of_the_separator_in_the_result) as input. If that comes from user input, it is problematic.
