### ISSUE TITLE
Configuration options documentation

### ISSUE THREAD

**Issue by luis-guimaraes-exoawk** [ajinabraham/njsscan#110]
https://github.com/ajinabraham/njsscan#configure-njsscan

The configuration options are not explained very well.

For example:

```yaml
- nodejs-extensions:
  - .js
```

Does this mean we need to add `.ts` as well if we have TypeScript files? Is TypeScript even supported?

The other options also lack needed information.

**Comment by ajinabraham** [comment]
Only server side javascript and html templates are supported. TypeScript is not supported and must be transpiled to JavaScript before scanning.

- nodejs-extensions: File extensions that contain server side javascript to scan
- template-extensions: File extension with html templates that needs to be scanned.
- ignore-filenames: File names to ignore
- ignore-paths: File paths to ignore 
- ignore-extensions: File extensions to ignore, used when nodejs-extensions is not defined.
 - ignore-rules: Ignore a particular njsscan rule
 - severity-filter: List only findings of certain severity

**Comment by luis-guimaraes-exoawk** [comment]
Thank you, I recommend adding that to the README
