### ISSUE TITLE
Report showing XSS vulnerability even though the code is fixed.

### ISSUE THREAD

**Issue by mahammadrafeek** [ajinabraham/njsscan#116]
const { xss } = require('express-xss-sanitizer');
app.use(xss());

This code removing the html tags and scripts from the request but still the njsscan showing vulnerabilities for the below code.

 ```
 router.post("/employee/data", async (req, res) => {

  const empData= await prepareEmployeeData(req.body);

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', 'attachment; filename=result.pdf');
  res.send(empData);

});
```

**Comment by ajinabraham** [comment]
This is possibly a false positive, the [rule](https://github.com/ajinabraham/njsscan/blob/master/njsscan/rules/semantic_grep/xss/xss_node.yaml) thinks that `req.body` is reaching the response via `res.send(empData);`

**Comment by mahammadrafeek** [comment]
@ajinabraham 
Is there any way we can fix it.?

**Comment by ajinabraham** [comment]
You can suppress the finding. See documentation.
