### ISSUE TITLE
Improve line numbers

### ISSUE THREAD

**Issue by prabhu** [ajinabraham/njsscan#12]
Will you be able to check the line numbers and ensure they are reported correctly?

For eg for the repo: https://github.com/conikeec/explnode

- redirect.js - line 7 is pointing to req.query.path instead of `redirect` - Possibly because the empty new lines are being trimmed by the tool?
- nosqli.js - findOne method is not being highlighted

The easiest method to spot line number issues is by scanning the project using my vscode extension which uses njsscan - https://marketplace.visualstudio.com/items?itemName=shiftleftsecurity.shiftleft-scan

**Comment by ajinabraham** [comment]
njsscan is reporting it as expected. It trace back the lines from source to sink (depends on the rules). It returns line numbers and match positions and not just a single line. we do not trim or modify the source.

**REDIRECT**
```
File: **/explnode-master/vulnerabilities/redirect.js
Match Position: 5 - 25
Line Number(s): 7: 11
Match String:     let followPath = req.query.path;

    if(req.session.isAuthenticated()){

        res.redirect('http://example.com/'+followPath); //false positive

    }else{

        res.redirect('/');


File: **/explnode-master/vulnerabilities/redirect.js
Match Position: 5 - 21
Line Number(s): 16: 17
Match String:     let url = encodeURI(req.query.url); //vulnerability

    res.redirect(url);
```
 **NOSQLI**
```
File: **/Downloads/explnode-master/vulnerabilities/nosqli.js
Match Position: 5 - 24
Line Number(s): 40: 45
Match String:     let name = req.body.name

    let myobj = { name: name };

    customers.findOne(myobj, function (err, result) {

        if (err) throw err;

        db.close();

        res.json(result)


File: **/explnode-master/vulnerabilities/nosqli.js
Match Position: 5 - 24
Line Number(s): 65: 69
Match String:     let myobj = { email: req.body.email, password: req.body.password };

    customers.findOne(myobj, function (err, result) {

        if (err) throw err;

        db.close();

        res.json(result)
```
The highlighting is not based on sinks, but based on minimal source to sink matching depending on the rules.

**Comment by prabhu** [comment]
Sounds good. Probably highlighting the sink method in vs code might make it more relevant for my use case. Thanks for clarifying.
