### ISSUE TITLE
Sarif output validation issue on latest release

### ISSUE THREAD

**Issue by luke88jones** [ajinabraham/njsscan#125]
Hi, we've found on the latest release we're getting an invalid output in the Sarif format. Specifically the validation error is `Error details: instance.runs[0].results[0] is not of a type(s) object`. After inspecting the results file the results array is now an array of arrays rather than objects as the schema requires. 

I've rolled back to 0.3.7 locally and the output is fine. We are using your Github action to run the scan which always targets master so I'm not able to use an older version and test a run on CI. 

Any help would be greatly appreciated.

**Comment by bakiyalakshmi1** [comment]
I'm also facing this issue. Please let me know if you need any details

**Comment by ajinabraham** [comment]
Thanks for reporting. This should be fixed in v0.4.2 and the latest action
