### ISSUE TITLE
Issue with running njsscan using ADO and pip

### ISSUE THREAD

**Issue by A30003153** [ajinabraham/njsscan#13]
Hey I am trying to run njsscan as part of AzureDevops CI step where I am using ubuntu latest agent with following script:

   ` python3 -V
    sudo apt install python3-pip
    pip3 install --upgrade setuptools
    pip3 install wheel
    pip3 install --upgrade njsscan
    njsscan -h`

Output:

`Collecting attrs>=19.3.0 (from semgrep==0.10.1->libsast>=1.0.6->njsscan)
  Downloading https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting ruamel.yaml==0.16.10 (from semgrep==0.10.1->libsast>=1.0.6->njsscan)
  Downloading https://files.pythonhosted.org/packages/a6/92/59af3e38227b9cc14520bf1e59516d99ceca53e3b8448094248171e9432b/ruamel.yaml-0.16.10-py2.py3-none-any.whl (111kB)
Collecting idna<3,>=2.5 (from requests>=2.22.0->libsast>=1.0.6->njsscan)
  Downloading https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl (58kB)
Collecting chardet<4,>=3.0.2 (from requests>=2.22.0->libsast>=1.0.6->njsscan)
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests>=2.22.0->libsast>=1.0.6->njsscan)
  Downloading https://files.pythonhosted.org/packages/e1/e5/df302e8017440f111c11cc41a6b432838672f5a70aa29227bf58149dc72f/urllib3-1.25.9-py2.py3-none-any.whl (126kB)
Collecting certifi>=2017.4.17 (from requests>=2.22.0->libsast>=1.0.6->njsscan)
  Downloading https://files.pythonhosted.org/packages/5e/c4/6c4fe722df5343c33226f0b4e0bb042e4dc13483228b4718baf286f86d87/certifi-2020.6.20-py2.py3-none-any.whl (156kB)
Collecting ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9" (from ruamel.yaml==0.16.10->semgrep==0.10.1->libsast>=1.0.6->njsscan)
  Downloading https://files.pythonhosted.org/packages/53/77/4bcd63f362bcb6c8f4f06253c11f9772f64189bf08cf3f40c5ccbda9e561/ruamel.yaml.clib-0.2.0-cp36-cp36m-manylinux1_x86_64.whl (548kB)
Building wheels for collected packages: pyyaml
  Running setup.py bdist_wheel for pyyaml: started
  Running setup.py bdist_wheel for pyyaml: finished with status 'done'
  Stored in directory: /home/vsts/.cache/pip/wheels/a7/c1/ea/cf5bd31012e735dc1dfea3131a2d5eae7978b251083d6247bd
Successfully built pyyaml
Installing collected packages: idna, chardet, urllib3, certifi, requests, attrs, ruamel.yaml.clib, ruamel.yaml, colorama, semgrep, pyyaml, libsast, njsscan
Successfully installed attrs-19.3.0 certifi-2020.6.20 chardet-3.0.4 colorama-0.4.3 idna-2.9 libsast-1.0.6 njsscan-0.0.8 pyyaml-5.3.1 requests-2.24.0 ruamel.yaml-0.16.10 ruamel.yaml.clib-0.2.0 semgrep-0.10.1 urllib3-1.25.9
+ njsscan -h
/home/vsts/work/_temp/57ac7207-16b8-4c19-831d-92f93364db0a.sh: line 7: njsscan: command not found`

Any suggestion.
I have also tried docker and that runs without any issue but it does not scan anything finishes without any output.
Thanks

**Comment by ajinabraham** [comment]
This is mostly an issue with your environment. We have tests running in latest ubuntu and mac. 
Regarding docker, njsscan won't report anything if it didn't find any issues. Try running it against a vulnerable repo like https://github.com/ajinabraham/dvna to verify that it is working fine.
