### ISSUE TITLE
Showing erro for NODE SQLI INJECTION even after formatting the query as bind parameter

### ISSUE THREAD

**Issue by aayushmall** [ajinabraham/njsscan#19]
I had a plain query written for Mysql using string concatenation in my application which got detected as vulnerable to SQL Injection using this tool.

I formatted the query as per mysql to prepare using the bind parameters for dynamically substituting the table name as follows and further using the sequelize to perform the query.

```
      const mysql = require('mysql2');
      mysql.format("SHOW COLUMNS FROM ?? WHERE field IN (:fields)", [`${db_name}.${table_name}`]);

      const result = await sequelize.query(query, {
        replacements: { fields },
        type: Models.rdbms.Sequelize.QueryTypes.SELECT
      });
```

After making these changes still these lines are shown as vulnerable to SQL Injection.

**Comment by ajinabraham** [comment]
This is a false positive, We will work on improving this rule.

**Comment by ajinabraham** [comment]
After checking against the code shared above. I do not see it being detected by njsscan.
