### ISSUE TITLE
Faulty node_nosqli_injection flags?

### ISSUE THREAD

**Issue by natlibfi-jonollil** [ajinabraham/njsscan#28]
Hi,

I got this weird error on possible node_nosqli_injection. I'm using this really simple sanitize "library" (https://www.npmjs.com/package/mongo-sanitize) to delete any keys with $ on them.

Here is the error message:
File: dist/mongo.js
Match Position: 5 - 7
Line Number(s): 276: 279
Match String:     const clean = (0, _mongoSanitize.sanitaze)(params.correlationId);
const result = await db.collection('queue-items').findOne({correlationId: clean});

Here is the code causing the error:
``` javascript
async function removeContent(params) {
    logger.log('info', `Removing content for id: ${params.correlationId}`);
    const clean = sanitaze(params.correlationId);

    const result = await db.collection('queue-items').findOne({correlationId: clean}); //ignore: node_nosqli_injection
    if (result) {
      const {_id: fileId} = await getFileMetadata({gridFSBucket, filename: clean});
      await gridFSBucket.delete(fileId);
      return true;
    }
  }
```

Any idea why it is throwing errors? Is it OK to just ignore?

https://github.com/ajinabraham/njsscan/blob/8f08aaf36fd1bf3e90161d6661dc0fd00316c1f8/njsscan/rules/semantic_grep/database/nosql_injection.yaml#L1-L69

**Comment by ajinabraham** [comment]
This might be a false positive. Looking into this.

**Comment by ajinabraham** [comment]
This is caught by https://github.com/ajinabraham/njsscan/blob/master/njsscan/rules/semantic_grep/database/nosql_find_injection.yaml
After looking into this, it appears to me like a false positive. I will work with semgrep upstream to see if we can whitelist sanitize function.

**Comment by ajinabraham** [comment]
@natlibfi-jonollil We have added support for `mongo-sanitize`  in njsscan 0.1.3
Following code will not be detected by njsscan
```
var sani = require('mongo-sanitize')
async function removeContent(params) {
    logger.log('info', `Removing content for id: ${params.correlationId}`);
    const clean = sani(params.correlationId);

    const result = await db.collection('queue-items').findOne({correlationId: clean}); //ignore: node_nosqli_injection
    if (result) {
      const {_id: fileId} = await getFileMetadata({gridFSBucket, filename: clean});
      await gridFSBucket.delete(fileId);
      return true;
    }
  }
```
