### ISSUE TITLE
Could not parse filename.ts as javascript

### ISSUE THREAD

**Issue by L3m0nb4tt3ry** [ajinabraham/njsscan#33]
This is a semgrep exception present in Errors node in json output, I have encountered this error in a lot of file and noticed that span is always

> start:
> col: 1 row: 1 
> end:
> col: 1 row: 1

All the files are syntactically correct the only difference from other files I noticed is the first line which looks something like this
`import { Request, Response } from 'express';`
the other files don't have curly brackets, not that its because of the brackets but just a difference i noticed while debugging. Could you please advise on what could be the issue here
code for reference
```
import { Request, Response, MyFunction} from 'express';
import generate from 'nanoid/generate';

const alphabet = xyz

const LONG_VALUE = 123*123;

export default (req: Request, res: Response, next: MyFunction=> {
...
myfunction
...
};

```

**Comment by ajinabraham** [comment]
njsscan cannot scan typescript. if you need to scan such files, you need to transpile it to JavaScript before scanning with njsscan
