### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by zricethezav** [ajinabraham/njsscan#36]
Hi @ajinabraham, thanks for this great SAST tool. Do you have any plans to add release notes so that it's easier to see what has been added/changed? Thanks!

**Comment by ajinabraham** [comment]
Yeah, sure. Was planning to do this for quite some time.

**Comment by ajinabraham** [comment]
All major changes will have a changelog associated will be published under https://github.com/ajinabraham/njsscan/releases/tag/0.1.7
