### ISSUE TITLE
"Semantic grep" seems to stop randomly without any output

### ISSUE THREAD

**Issue by joelngwt** [ajinabraham/njsscan#37]
njsscan version: 0.1.8
OS: Ubuntu 18
Python 3.9.0

Commands:
```
$ sudo apt-get update
$ sudo apt install python3-pip
$ pip3 install njsscan
$ njsscan .
- Pattern Match ████████████████████████████████████████████████████████████ 120
- Semantic Grep ███████████████████████ 550
```

It always randomly stops somewhere before 600, not sure why this is happening?

**Comment by ajinabraham** [comment]
Can you isolate the file that is causing this issue? There might be an expensive rule processing happening with semgrep.

**Comment by joelngwt** [comment]
Hmm, it seems to happen in every single file that I have. Example file `theme.ts`:

```
import { DefaultTheme } from 'styled-components';

const theme: DefaultTheme = {
  borderRadius: '5px',
  colors: {
    main: 'hsl(220, 60%, 49%)',
  },
};

export default theme;
```

Result: 

```
$ njsscan theme.ts
- Pattern Match ████████████████████████████████████████████████████████████ 1
- Semantic Grep █████████████████████████████████ 196
```

Another one, `tokenHelper.ts`:

```
export function saveBearerToken(token: string): void {
  localStorage.setItem('bearerToken', token);
}

export function removeBearerToken(): void {
  localStorage.removeItem('bearerToken');
}
```

Result:

```
$ njsscan tokenHelper.ts
- Pattern Match ████████████████████████████████████████████████████████████ 1
- Semantic Grep █████████████████████████████████ 198
```

**Comment by ajinabraham** [comment]
So njsscan is completing without result. I was under the impression that njsscan is getting stuck while scanning. The result you are seeing is expected. You are trying to scan typescript with njsscan which is not supported. you need to provide javascript files to njsscan.

**Comment by joelngwt** [comment]
Hmm, I tried it on a javascript file too, and I get similar results.

Should the bar for semantic grep reach the end to align with the pattern match bar? It's not supposed to stop in the middle, is it? It's kind of hard to tell if it's done done, or it exited halfway.

`scrollHandler.js`:
```
let scrollHandlers = [];

class ScrollHandler {
  static register(handler) {
    scrollHandlers.push(handler);
  }

  static remove(handler) {
    scrollHandlers = scrollHandlers.filter(h => h !== handler);
  }
}

window.addEventListener('scroll', (e) => {
  scrollHandlers.forEach(handler => handler(e));
}, true);

export default ScrollHandler;
```

Result:
```
$ njsscan scrollHandler.js
- Pattern Match ████████████████████████████████████████████████████████████ 1
- Semantic Grep ████████████████████████████████████ 213
```

**Comment by ajinabraham** [comment]
This is expected. You will see an output from njsscan only if it detects insecure code. The semgrep progress bar is non deterministic. It is based on function execution time.

**Comment by joelngwt** [comment]
Ah okay, got it! The examples worked.

Thank you!
