### ISSUE TITLE
Knex support

### ISSUE THREAD

**Issue by adrianhelvik** [ajinabraham/njsscan#38]
Hi! Great library!

Could you add support for detecting SQL injection for Knex? Some examples: 

    *.raw("select * from users where email ='" + unsafe + "'")
    *.raw(`select * from users where email = '${unsafe}'`)
    *.whereRaw("email = '" + unsafe} + "'")
    *.whereRaw(`email = '${unsafe}'`)

**Comment by ajinabraham** [comment]
Sure, thanks for the heads up.

**Comment by ajinabraham** [comment]
Added in 0.1.19
