### ISSUE TITLE
GithubActions workflow output

### ISSUE THREAD

**Issue by davidkhala** [ajinabraham/njsscan#4]
I have configured accordingly with proper syntax. 

But in my repository github Actions build log we could only see

```
...
Pattern Match ██████████████████████████████████████████████████████████ 120
- Pattern Match ██████████████████████████████████████████████████████████ 121
- Pattern Match ███████████████████████████████████████████████████████████ 122
- Pattern Match ███████████████████████████████████████████████████████████ 123
- Pattern Match ████████████████████████████████████████████████████████████ 124
- Semantic Grep  0
- Semantic Grep  1
- Semantic Grep █ 2
- Semantic Grep █ 3
- Semantic Grep ██ 4
- Semantic Grep ██ 5
- Semantic Grep ███ 6
- Semantic Grep ████ 7
- Semantic Grep ████ 8
- Semantic Grep █████ 9
- Semantic Grep █████ 10
- Semantic Grep ██████ 11
- Semantic Grep ██████ 12
- Semantic Grep ███████ 13

```

Then where is the scan report?

**Comment by ajinabraham** [comment]
if it finds an issue with Error severity, it will fail the build. see for example https://github.com/ajinabraham/Node.Js-Security-Course/runs/702265686?check_suite_focus=true#step:4:63

if you want to hide the progress bar, you could use `--json`

```
with:
        args: '--json .'
```

**Comment by davidkhala** [comment]
Thanks, could we modify the warning threshold of severity?

**Comment by davidkhala** [comment]
> Modify warning? I do not understand you. Do you want to fail build on warning?

Yes it is what I mean, Or any log option that could display all information including good practice, better-to-have and must-fix

**Comment by ajinabraham** [comment]
So currently we fail the build only on `error` warning and `info` will not.  For missing good practices use the flag `--missing-controls`. I will consider an enhancement to fail on warning as well.

**Comment by ajinabraham** [comment]
actually, we fail build on `error` or `warning`.

https://github.com/ajinabraham/njsscan/blob/master/njsscan/__main__.py#L91

**Comment by ajinabraham** [comment]
Having said that, this behaviour is changed in 0.0.8
warning will have exit code zero.
For non zero exit code use `-w` flag.
