### ISSUE TITLE
Showing Info severity issues

### ISSUE THREAD

**Issue by islasjuanp** [ajinabraham/njsscan#41]
Hi @ajinabraham, first at all I want to thank you for the excellent tools that you've built. 

Is there any option/argument for the command line or any configuration for `.njsscan` file to enable the list of issues with INFO severity?

**Comment by ajinabraham** [comment]
Hi @islasjuanp 

We have very few INFO rules `https://github.com/ajinabraham/njsscan/search?l=YAML&q=info`

For seeing most of them, you need to run njsscan with the `--missing-controls` flag.

To list issues with INFO only severity, you need to ignore other rules in `.njsscan` using `ignore-rules:` key or use the njsscan python API to get and format results as you would like.

**Comment by islasjuanp** [comment]
Thanks @ajinabraham. It helped me a lot
