### ISSUE TITLE
[Feature-request] Be able to supply a .njsscan config file instead of having it at the source directory root

### ISSUE THREAD

**Issue by Matthew-Smith** [ajinabraham/njsscan#48]
We don't like polluting our source directory with dot files so it would be really nice to be able to specify the config file location as an argument to the CLI:

```sh
> njsscan --config=config_files/.njscan ./src
 ```

**Comment by ajinabraham** [comment]
It is a standard practice to have dotfiles in the root directories. I will see if we can support custom config location.

**Comment by ajinabraham** [comment]
Addressed in 0.2.2
