### ISSUE TITLE
Test repo for improving the tool

### ISSUE THREAD

**Issue by prabhu** [ajinabraham/njsscan#5]
Here is a test repo with 9 vulnerabilities. The tool can detect 4 which is a big improvement compared to nodejsscan which was zero!

https://github.com/conikeec/explnode

Can you take a look and let me know if it is possible to enhance the rules and detect at least 7 or all 9?

**Comment by ajinabraham** [comment]
Thanks for opening the issue. Some of these can be detected with some minor rule tweaks.
Few of them depends on bug fixes in semgrep

**Comment by ajinabraham** [comment]
Fixed in https://github.com/ajinabraham/njsscan/pull/11
