### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by zain-CSsol** [ajinabraham/njsscan#50]
Hello, i installed njsscan on laptop with following configurations

1. HP Core i5 7th Gen
2. RAM 16 GB
3. Python 3.7
4. Windows 10

after issuing the following command to scan the file i get error

**njsscan test.js**

TypeError: 'NoneType' object is not subscriptable

![image](https://user-images.githubusercontent.com/77674107/107508066-488d9d80-6bc2-11eb-9b7e-0f1c442e9d97.png)

**Comment by ajinabraham** [comment]
What version of njsscan and semgrep are you using?
```
pip freeze
```
will give you that.

Also can you share a problematic js file to replicate this issue?

**Comment by zain-CSsol** [comment]
> What version of njsscan and semgrep are you using?
> 
> ```
> pip freeze
> ```
> 
> will give you that.
> 
> Also can you share a problematic js file to replicate this issue?

my semgrep version is 0.39.1 and njsscan 0.2.2
[test.zip](https://github.com/ajinabraham/njsscan/files/5963489/test.zip)

the zip file has been attached which includes test.js file for testing

**Comment by ajinabraham** [comment]
I think you have wrong version of semgrep.  njsscan 0.2.2 needs semgrep==0.38.0

**Comment by zain-CSsol** [comment]
thanks for your very precious help, actually now with your help i came to know that the problem is not in the njsscan, but the actual problem is in the semgrep itself, the semgrep is not able to download configurations successfully, it throws error, and njsscan is using semgrep for some reasons so that's why the exception under discussion is being encountered.
