### ISSUE TITLE
[Feature-request] output report as html

### ISSUE THREAD

**Issue by a-boulafia** [ajinabraham/njsscan#59]
Hello, i would like to know if you would consider a new output option to html tables (similar to the actual ascii tables)
It could be useful to be able to see reports as uploaded artifacts online
Thanks

**Comment by ajinabraham** [comment]
This is easily doable as we use tabulate. I will add it in the next release. But if you are looking for fancy HTML reports, take a look at https://github.com/ajinabraham/nodejsscan

**Comment by ajinabraham** [comment]
Addressed in 0.2.5
https://github.com/ajinabraham/njsscan/releases/tag/0.2.5
