### ISSUE TITLE
Add ability to know which files are being scanned.

### ISSUE THREAD

**Issue by vsviridov** [ajinabraham/njsscan#62]
Currently when I run the tool in the project folder with some boiler plate code it takes 8 minutes to complete and I have no transparency into what files are actually scanned...

It's difficult to configure exclusions when there's no transparency into the tool operation.

**Comment by ajinabraham** [comment]
It's not a common practice to list file names during a cli SAST scan (Ref: bandit, brakeman ..). We do have a progress bar for default cli and html output format.
