### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by o8e** [ajinabraham/njsscan#66]
What is the feasibility of being able to scan TypeScript? Considering Semgrep itself supports it.

I find that when transpiling it and scanning the build files, most if not all of the results are false positives so it's not looking like a viable option at the moment.

**Comment by ajinabraham** [comment]
In the short term, we do not have any plans to support TypeScript. The only option is to transpile to JavaScript.
This is a major work and will require writing and testing equivalent TS rules for https://github.com/ajinabraham/njsscan/tree/master/njsscan/rules/semantic_grep

We may revisit this if we get sponsors or contributors interested in taking this up.
