### ISSUE TITLE
Error importing sonarqube report into sonar

### ISSUE THREAD

**Issue by kmlp10** [ajinabraham/njsscan#68]
There is an error in generated sonarqube report and details about the problem is present in below link,
https://community.sonarsource.com/t/error-njsscan-repot-upload-throught-externalissuesreportpath/40133

Please help to fix it.

Regards
Muthu

**Comment by ajinabraham** [comment]
Hi @kmlp10 SonarQube support is contributed by @cynthiabaran 

@cynthiabaran any ideas what might be happening here?

**Comment by sorx00** [comment]
I've got the same error with wrong line position.
On the SonarSource community page, kmlp10 user suggested a variant of modifying the result with the jq tool, but the output JSON has a different structure.
I use this script:
```
jq '(.issues[] | .primaryLocation.textRange | .endColumn) |= . - 1' njsscan-report.json
```

**Comment by JordanKergoat** [comment]
Hi,
I suggested a fix for this issue.  I would be interested to get a new tag as well to publish a new docker image please.
thanks in advance

**Comment by ajinabraham** [comment]
Fixed in https://github.com/ajinabraham/njsscan/pull/97/files

**Comment by JordanKergoat** [comment]
@ajinabraham thanks for the merge, the fix has been tested successfully, could you please tag this commit 0.3.3 ?

Thanks a lot

**Comment by ajinabraham** [comment]
Done
