### ISSUE TITLE
node_username rule overly broad for ERROR

### ISSUE THREAD

**Issue by jayvdb** [ajinabraham/njsscan#80]
This rule matches `.*user.*`, and there are many uses of "user" which are not a username.

For example it is triggered by https://github.com/swift-nav/libsbp/blob/e688ede22070e455cd941216e237b0223473960d/javascript/sbp/user.js#L45

I suggest `.*username.*` should trigger an error, and *maybe*  `.*user.*` only a warning (a new rule called `node_user`?).

**Comment by MichaelFroeschen** [comment]
Another example: `const LITERAL_CHECK_USER_ROLE = 'CheckUserRole';`
This also applies to the node_password rule which fires if `.*pass.*` matches.
In my case it fires on a assigment to a prop of the variable 'passive'

**Comment by ajinabraham** [comment]
This is a false positive in your case. You can [suppress](https://github.com/ajinabraham/njsscan#suppress-findings) these findings. We use `*user*` and  `*password*` to be aggressive in detecting possible secrets.

But I will change username severity to warning in the next release.
