### ISSUE TITLE
squirrelly_template rule

### ISSUE THREAD

**Issue by nbeguier** [ajinabraham/njsscan#81]
Hello,

According to this rule : https://github.com/ajinabraham/njsscan/blob/c6ea106da3864b9a66355c47a31a9c948ca8bcba/njsscan/rules/pattern_matcher/template_rules.yaml#L72 , using this syntax result to a XSS: 
```
{{ someUserInput | safe }}
```

I don't find any flaw in Squirrelly.js that indicate such a behavior, are your sure about it ?

**Comment by ajinabraham** [comment]
https://squirrelly.js.org/docs/syntax/filters/#the-safe-flag 
If `someUserInput` is controlled by user, this will result in XSS if `safe` flag is used.

**Comment by nbeguier** [comment]
Indeed, I thought it was to escape the value, not to indicating that the value is "safe" !
Thanks a lot 👍🏻
