### ISSUE TITLE
False positive in sql injection rule

### ISSUE THREAD

**Issue by wallali** [ajinabraham/njsscan#82]
Hi,
the code below seems to create a false positive match in `ajinabraham.njsscan.sql_injection.node_sqli_injection`.

I'm not sure what can be changed in the javascript code to avoid a match, though the code is safe. 
I'm not a semgrep expert but I think the rule is maybe too general.

```js
router.get('/:id', async function (req, res) {
  const pg = pgClient.getPostgresClient();
  const ids = req.params.id;
  const offset = 0;
  const limit = 1;

  const validInput = validateInput({ offset, limit, ids });
  if (validInput.error) return res.json(validInput);
  
  const path = req.baseUrl;
  const idln  = ids.length;
  const sqlQuery = genQueryString(path, idln);

  const value = queryValues({ offset, limit, ids });
  const response = await pg.query(sqlQuery, value);

  res.json(response.rows.map(rowToFormattedObject));
});
```

https://semgrep.dev/s/Rynv

**Comment by ajinabraham** [comment]
If injection is not possible, you can consider it as a false positive. The rule only looks for user input reaching `query()` as a part of the SQL query. It does not have insights into business logic checks to prevent an injection.
