### ISSUE TITLE
--html no longer works?

### ISSUE THREAD

**Issue by erzz** [ajinabraham/njsscan#89]
**No artifact created**
```
njsscan --html -o njsscan.html tests/node-sample-app
```

**Artifact created**
```
njsscan --json -o njsscan.json tests/node-sample-app
```

Tested on 0.2.9 and 0.3.1 locally and in github actions

**Comment by ajinabraham** [comment]
Thanks for the report, I will take a look. Any chance `tests/node-sample-app` is available on a public repo?

**Comment by ajinabraham** [comment]
Also works fine for me on the latest version

**Comment by erzz** [comment]
Just a note to say also tested and now working. Thanks for the fix! @ajinabraham
