### ISSUE TITLE
Semgrep & ParseErrors

### ISSUE THREAD

**Issue by L3m0nb4tt3ry** [ajinabraham/njsscan#9]
It seems like there are a lot of instances where semgrep is failing and printing verbose error message on the console.
e.g. I got a few errors like
`bad: somecode`  
`bad: somecode`  
`bad: somecode `  
And also a huge json highlighted in red, printed FatalError like
`[{'data': {'check_id': 'FatalError', 'path': `
I understand the semgrep wont be perfect, can we hide the errors occurred during runtime ?

**Comment by entrptaher** [comment]
I also ran it in a reactjs repository, and the scan crashed like this.  
  
The error is pretty straightforward,

```
WIERD end of file in regexp
```

![](https://user-images.githubusercontent.com/8284972/84772336-9d115680-affc-11ea-905c-e42204d9eff4.png)

**Comment by ajinabraham** [comment]
I have opened an issue upstream.

**Comment by ajinabraham** [comment]
@entrptaher @L3m0nb4tt3ry This should already be fixed in latest njsscan.

Can you try `pip install --upgrade njsscan libsast` and try scanning again ?

**Comment by ajinabraham** [comment]
The `huge json highlighted in red` will be fixed in 0.0.8

**Comment by L3m0nb4tt3ry** [comment]
@ajinabraham Can confirm the semgrep bad ones are not there anymore. I was using the previous docker image and may be missed the latest update, after fetching it again, works fine.

**Comment by ajinabraham** [comment]
You shouldn't be seeing 
```
bad: somecode
bad: somecode
bad: somecode
```
but the red highlighted critical errors will be still there. Expect a complete fix once 0.0.8 is released.

**Comment by L3m0nb4tt3ry** [comment]
Yes can confirm, sorry for hijacking the threat but will 0.0.8 also include changes to semgrep rules to catch xss, code execution issue from explnode, I am also interested in creating custom rules, let me know If i can contribute but I have limited knowledge in semgrep, I am still learning

**Comment by ajinabraham** [comment]
Yes 0.0.8 will have rule tweaks to catch the missing vulns from explnode.

It's quite easy to work on the rules.
Here are the rules we use: https://github.com/ajinabraham/njsscan/tree/master/njsscan/rules/semantic_grep

To test the rule against corresponding code, you can use: https://semgrep.live/editor
More documentation about semgrep syntax here: https://github.com/returntocorp/semgrep/blob/develop/docs/configuration-files.md#pattern

**Comment by ajinabraham** [comment]
Fixed in https://github.com/ajinabraham/njsscan/pull/11
