### ISSUE TITLE
future request: Add junit format output

### ISSUE THREAD

**Issue by armanbaghajyan** [ajinabraham/njsscan#90]
Is it possible to have outputs in junit format?
Also, it would be great to have outputs in two formats let's say default and something else. For example in ci/cd integration sometimes we need to show the resulting output and send output into sonarqube.

**Comment by ajinabraham** [comment]
The following output formats are supported at this time.
```
 --json                set output format as JSON
  --sarif               set output format as SARIF 2.1.0
  --sonarqube           set output format compatible with SonarQube
  --html     
  ```
 There is no plans for junit format. PRs are welcome though.
