### ISSUE TITLE
False positives with node_username

### ISSUE THREAD

**Issue by snyamathi** [ajinabraham/njsscan#93]
```js
const UserIcon = () => { /* return React.createElement(...) */ };
UserIcon.displayName = 'xxx';
```

The `ajinabraham.njsscan.hardcoded_secrets.node_username` rule seems to match against simple variables names such as this hypothetical react component.

**Comment by ajinabraham** [comment]
This is a false positive you could configure to ignore.
The rule we use is simple `regex: '(?i:.*user.*)'`
It looks for variables that contains the the term `user`
