### ISSUE TITLE
Getting error while executing njsscan

### ISSUE THREAD

**Issue by sumitsharma16** [ajinabraham/njsscan#95]
Hi

We are getting the below error. It runs for a while and after that it gives the error. Please let us know the solution or the reason.

########################### error ###############################################################

Pattern Match ██████████████████████████████████████████████████████████ 97
- Pattern Match ███████████████████████████████████████████████████████████ 98
- Pattern Match ████████████████████████████████████████████████████████████ 99
20:48:30 - Semantic Grep  0
- Semantic Grep  1
- Semantic Grep  2
- Semantic Grep  3
- Semantic Grep  4
- Semantic Grep  5
- Semantic Grep  6
- Semantic Grep  7
- Semantic Grep  8
- Semantic Grep  9
- Semantic Grep  10
- Semantic Grep  11
- Semantic Grep  12
Exception in thread Thread-1:
20:48:30 Traceback (most recent call last):
20:48:30   File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
20:48:30     self.run()
20:48:30   File "/usr/lib64/python3.7/threading.py", line 870, in run
20:48:30     self._target(*self._args, **self._kwargs)
20:48:30   File "/usr/local/lib/python3.7/site-packages/libsast/common.py", line 45, in myrunner
20:48:30     ret[0] = function(*args, **kwargs)
20:48:30   File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/helpers.py", line 59, in invoke_semgrep
20:48:30     **kwargs,
20:48:30   File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 369, in main
20:48:30     deep,
20:48:30   File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 155, in run_rules
20:48:30     target_manager, filtered_rules, dump_command_for_core, deep
20:48:30   File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 759, in invoke_semgrep
20:48:30     rules, target_manager, dump_command_for_core, deep
20:48:30   File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 703, in _run_rules_direct_to_semgrep_core
20:48:30     returncode = runner.execute()
20:48:30   File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 283, in execute
20:48:30     rc = asyncio.run(self._stream_subprocess())
20:48:30   File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
20:48:30     return loop.run_until_complete(main)
20:48:30   File "/usr/lib64/python3.7/asyncio/base_events.py", line 587, in run_until_complete
20:48:30     return future.result()
20:48:30   File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 246, in _stream_subprocess
20:48:30     preexec_fn=setrlimits_preexec_fn,
20:48:30   File "/usr/lib64/python3.7/asyncio/subprocess.py", line 217, in create_subprocess_exec
20:48:30     stderr=stderr, **kwds)
20:48:30   File "/usr/lib64/python3.7/asyncio/base_events.py", line 1544, in subprocess_exec
20:48:30     bufsize, **kwargs)
20:48:30   File "/usr/lib64/python3.7/asyncio/unix_events.py", line 193, in _make_subprocess_transport
20:48:30     self._child_watcher_callback, transp)
20:48:30   File "/usr/lib64/python3.7/asyncio/unix_events.py", line 941, in add_child_handler
20:48:30     "Cannot add child handler, "
20:48:30 RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
20:48:30 
20:48:30 - Semantic Grep  13
20:48:30 Traceback (most recent call last):
20:48:30   File "/usr/local/bin/njsscan", line 8, in <module>
20:48:30     sys.exit(main())
20:48:30   File "/usr/local/lib/python3.7/site-packages/njsscan/__main__.py", line 76, in main
20:48:30     args.config,
20:48:30   File "/usr/local/lib/python3.7/site-packages/njsscan/njsscan.py", line 44, in scan
20:48:30     result = scanner.scan()
20:48:30   File "/usr/local/lib/python3.7/site-packages/libsast/scanner.py", line 65, in scan
20:48:30     self.options).scan(valid_paths)
20:48:30   File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/semantic_sgrep.py", line 41, in scan
20:48:30     self.format_output(sgrep_out)
20:48:30   File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/semantic_sgrep.py", line 46, in format_output
20:48:30     self.findings['errors'] = results['errors']
20:48:30 TypeError: 'NoneType' object is not subscriptable
20:48:30 Future exception was never retrieved
20:48:30 future: <Future finished exception=CancelledError()>
20:48:30 Traceback (most recent call last):
20:48:30   File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
20:48:30     self.run()
20:48:30   File "/usr/lib64/python3.7/threading.py", line 870, in run
20:48:30     self._target(*self._args, **self._kwargs)
20:48:30   File "/usr/local/lib/python3.7/site-packages/libsast/common.py", line 45, in myrunner
20:48:30     ret[0] = function(*args, **kwargs)
20:48:30   File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/helpers.py", line 59, in invoke_semgrep
20:48:30     **kwargs,
20:48:30   File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 369, in main
20:48:30     deep,
20:48:30   File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 155, in run_rules
20:48:30     target_manager, filtered_rules, dump_command_for_core, deep
20:48:30   File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 759, in invoke_semgrep
20:48:30     rules, target_manager, dump_command_for_core, deep
20:48:30   File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 703, in _run_rules_direct_to_semgrep_core
20:48:30     returncode = runner.execute()
20:48:30   File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 283, in execute
20:48:30     rc = asyncio.run(self._stream_subprocess())
20:48:30   File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
20:48:30     return loop.run_until_complete(main)
20:48:30   File "/usr/lib64/python3.7/asyncio/base_events.py", line 587, in run_until_complete
20:48:30     return future.result()
20:48:30   File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 246, in _stream_subprocess
20:48:30     preexec_fn=setrlimits_preexec_fn,
20:48:30   File "/usr/lib64/python3.7/asyncio/subprocess.py", line 217, in create_subprocess_exec
20:48:30     stderr=stderr, **kwds)
20:48:30   File "/usr/lib64/python3.7/asyncio/base_events.py", line 1544, in subprocess_exec
20:48:30     bufsize, **kwargs)
20:48:30   File "/usr/lib64/python3.7/asyncio/unix_events.py", line 193, in _make_subprocess_transport
20:48:30     self._child_watcher_callback, transp)
20:48:30   File "/usr/lib64/python3.7/asyncio/unix_events.py", line 941, in add_child_handler
20:48:30     "Cannot add child handler, "
20:48:30 RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
20:48:30 
20:48:30 During handling of the above exception, another exception occurred:
20:48:30 
20:48:30 Traceback (most recent call last):
20:48:30   File "/usr/lib64/python3.7/asyncio/base_subprocess.py", line 171, in _connect_pipes
20:48:30     proc.stdout)
20:48:30   File "/usr/lib64/python3.7/asyncio/base_events.py", line 1452, in connect_read_pipe
20:48:30     await waiter
20:48:30 concurrent.futures._base.CancelledError
20:48:30 + true

**Comment by ajinabraham** [comment]
This looks like it's coming from semgrep. Can you open an issue upstream?
https://github.com/returntocorp/semgrep

**Comment by sumitsharma16** [comment]
NJSSCAN VERSION : njsscan: v0.3.2 | Ajin Abraham | opensecurity.in
Semgrep ticket : https://github.com/returntocorp/semgrep/issues/5758

**Comment by sumitsharma16** [comment]
Hi 
Any update ?

**Comment by ajinabraham** [comment]
We won’t be able to provide an update on the semgrep issue. You need to wait for semgrep team to respond.

**Comment by toastyghost** [comment]
Was this issue introduced in a particular version of semgrep? And if so, is it possible to pin the dependency to a specific prior version that doesn't have the issue until they address it? I'm not super familiar with how Python deps work, but this is an approach I've used in Node projects a number of times.

**Comment by ajinabraham** [comment]
@sumitsharma16 Can you share a test data to reproduce this issue?

**Comment by spmishra121** [comment]
Hi @ajinabraham ,
Please find the version of njsscan...

**[root@ip-10-25-48-63 workspace]# njsscan --version

njsscan: v0.3.3 | Ajin Abraham | opensecurity.in
[root@ip-10-25-48-63 workspace]#**


**Result of njsscan**
[root@ip-10-25-48-63 workspace]# njsscan .
- Pattern Match ████████████████████████████████████████████████████████████ 134
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/libsast/common.py", line 45, in myrunner
    ret[0] = function(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/helpers.py", line 59, in invoke_semgrep
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 369, in main
    deep,
  File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 155, in run_rules
    target_manager, filtered_rules, dump_command_for_core, deep
  File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 759, in invoke_semgrep
    rules, target_manager, dump_command_for_core, deep
  File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 703, in _run_rules_direct_to_semgrep_core
    returncode = runner.execute()
  File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 283, in execute
    rc = asyncio.run(self._stream_subprocess())
  File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 246, in _stream_subprocess
    preexec_fn=setrlimits_preexec_fn,
  File "/usr/lib64/python3.7/asyncio/subprocess.py", line 217, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 1544, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib64/python3.7/asyncio/unix_events.py", line 193, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/lib64/python3.7/asyncio/unix_events.py", line 941, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached

- Semantic Grep  19
Traceback (most recent call last):
  File "/usr/local/bin/njsscan", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/njsscan/__main__.py", line 76, in main
    args.config,
  File "/usr/local/lib/python3.7/site-packages/njsscan/njsscan.py", line 44, in scan
    result = scanner.scan()
  File "/usr/local/lib/python3.7/site-packages/libsast/scanner.py", line 65, in scan
    self.options).scan(valid_paths)
  File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/semantic_sgrep.py", line 41, in scan
    self.format_output(sgrep_out)
  File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/semantic_sgrep.py", line 46, in format_output
    self.findings['errors'] = results['errors']
TypeError: 'NoneType' object is not subscriptable
Future exception was never retrieved
future: <Future finished exception=CancelledError()>
Traceback (most recent call last):
  File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/libsast/common.py", line 45, in myrunner
    ret[0] = function(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/libsast/core_sgrep/helpers.py", line 59, in invoke_semgrep
    **kwargs,
  File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 369, in main
    deep,
  File "/usr/local/lib/python3.7/site-packages/semgrep/semgrep_main.py", line 155, in run_rules
    target_manager, filtered_rules, dump_command_for_core, deep
  File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 759, in invoke_semgrep
    rules, target_manager, dump_command_for_core, deep
  File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 703, in _run_rules_direct_to_semgrep_core
    returncode = runner.execute()
  File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 283, in execute
    rc = asyncio.run(self._stream_subprocess())
  File "/usr/lib64/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/semgrep/core_runner.py", line 246, in _stream_subprocess
    preexec_fn=setrlimits_preexec_fn,
  File "/usr/lib64/python3.7/asyncio/subprocess.py", line 217, in create_subprocess_exec
    stderr=stderr, **kwds)
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 1544, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib64/python3.7/asyncio/unix_events.py", line 193, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/lib64/python3.7/asyncio/unix_events.py", line 941, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/base_subprocess.py", line 171, in _connect_pipes
    proc.stdout)
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 1452, in connect_read_pipe
    await waiter
concurrent.futures._base.CancelledError




**Semgrep Version:** 
Installing collected packages: semgrep
  Attempting uninstall: semgrep
    Found existing installation: semgrep 0.104.0
    Uninstalling semgrep-0.104.0:
      Successfully uninstalled semgrep-0.104.0
ERROR: libsast 1.5.2 requires semgrep==0.104.0, but you'll have semgrep 0.110.0 which is incompatible.
**Successfully installed semgrep-0.110.0**
[root@ip-10-25-48-63 workspace]#


**Semgrep Result**

[root@ip-10-25-48-63 workspace]# semgrep --config=auto .
Fetching rules from https://semgrep.dev/registry.

Scanning across multiple languages:
    <multilang> |  55 rules × 330 files
             ts | 196 rules × 132 files
           json |   4 rules ×  10 files
             js | 185 rules ×   4 files
           bash |   5 rules ×   3 files
     dockerfile |   5 rules ×   2 files

  100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|481/481 tasks

Findings:

  seeder-scripts/default-collection-views/default-collection-views-seeder-scripts/Dockerfile
     dockerfile.security.missing-user.missing-user
        By not specifying a USER, a program in the container may run as 'root'. This is a security
        hazard. If an attacker can control a process running as root, they may have control over the
        container. Ensure that the last USER in a Dockerfile is a USER other than 'root'.
        Details: https://sg.run/Gbvn

         18┆ CMD ["node", "default-collection-views-seeder.js"]


  src/common/handlers/dlss/dlss.service.ts
     javascript.express.security.audit.xss.direct-response-write.direct-response-write
        Detected directly writing to a Response object from user-defined input. This bypasses any
        HTML escaping and may expose your application to a Cross-Site-scripting (XSS) vulnerability.
        Instead, use 'resp.render()' to render safely escaped HTML.
        Details: https://sg.run/vzGl

        139┆ return res.status(200).send(result);
          ⋮┆----------------------------------------
        335┆ return res.status(200).send(result);

Some files were skipped or only partially analyzed.
  Scan skipped: 14 files larger than 1.0 MB, 40428 files matching .semgrepignore patterns
  For a full list of skipped files, run semgrep with the --verbose flag.

Ran 1197 rules on 165 files: 3 findings.
[root@ip-10-25-48-63 workspace]#

**Comment by spmishra121** [comment]
Is it required python 3.7 as a default version? Mine default version is 2.7.

**Comment by spmishra121** [comment]
@ajinabraham , Any update on this ticket?

**Comment by ajinabraham** [comment]
This is an upstream issue and requires a fix upstream by semgrep

**Comment by spmishra121** [comment]
When I was installing semgrep, I had observed one error... Highlighted in Bold... Please look into this...

Semgrep Version:
Installing collected packages: semgrep
Attempting uninstall: semgrep
Found existing installation: semgrep 0.104.0
Uninstalling semgrep-0.104.0:
Successfully uninstalled semgrep-0.104.0
**ERROR: libsast 1.5.2 requires semgrep==0.104.0, but you'll have semgrep 0.110.0 which is incompatible.**
Successfully installed semgrep-0.110.0

**Comment by spmishra121** [comment]
I had tested this issue using semgrep individual version 110. But apart from that if njssscan version is 0.3.1 and semgrep version is 0.104.0, The same error is coming.

**Comment by spmishra121** [comment]
@ajinabraham , Seems that above error is when output type is html.
like  **njsscan . --json -o test1.json** produce no error
while  **njsscan . --html -o test.html** produce the same  error as above.
